In [51]:
import numpy as n

In [52]:
a=n.array([1,2,3],dtype= 'int16')
print(a)

[1 2 3]


In [7]:

b=np.array([[1.0,2.0,3.0],[4,5,6]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.shape


(3,)

In [12]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('float64')

In [19]:
a.itemsize

2

In [20]:
a.nbytes

6

In [21]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
c.shape


(2, 7)

In [23]:
c[1,5]

13

In [24]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
c[0,1:6:2]

array([2, 4, 6])

In [27]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
d[1,1,0]

7

In [30]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [33]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [35]:
np.full_like(c,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [36]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.44130813, 0.12987836],
       [0.34034143, 0.09981501],
       [0.07532106, 0.00535499],
       [0.72066439, 0.43533831]])

In [37]:
np.random.random_sample(c.shape)

array([[0.19355085, 0.23283516, 0.96241917, 0.17976881, 0.56073882,
        0.01020377, 0.80694388],
       [0.70858057, 0.62617322, 0.39291048, 0.09353221, 0.65015887,
        0.85891047, 0.36704257]])

In [41]:
np.random.randint(4,8,size=(3,4))

array([[4, 6, 6, 6],
       [7, 7, 5, 4],
       [5, 7, 6, 4]])

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [49]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Linear Algebra and Statistics to be tried 

To load data from file 
np.genfromtxt('data.txt', delimiter=',')